export const forum = [
  ['Thông báo', 2],
  ['Thắc mắc & Góp ý',3],
  ['Tin tức INet', 26],
  ['Review sản phẩm',27],
  ['Overclocking & Cooling',6],
  ['Modding',151],
  ['AMD',25],
  ['Intel',24],
  ['Mainboard & Memory',7],
  ['Đồ họa máy tính',8],
  ['Phần cứng chung', 9],
  ['miniPC',277],
  ['Tự build máy chạy macOS',265],
  ['Thiết bị ngoại vi & Phụ kiện',30],
  ['Phần mềm',13],
  ['Trường đua',15],
  ['Thảo luận chung',11],
  ['DOTA2',245],
  ['League of Legends',253],
  ['Garena - Liên Quân Mobile',254],
  ['MMO -- Game Online',12],
  ['Máy tính xách tay',47],
  ['Các sản phẩm Apple',108],
  ['Máy tính chuyên dụng',112],
  ['Thiết bị di động',32],
  ['Đồ điện tử & Thiết bị gia dụng',10],
  ['Multimedia',31],
  ['Mạng gia đình & Doanh nghiệp nhỏ',273],
  ['Tư vấn xây dựng thương hiệu',312],
  ['Tư vấn kinh doanh online',311],
  ['DELL - Thông tin sản phẩm và dịch vụ chính hãng',213],
  ['Hoanghamobile.com',222],
  ['We can do (việc làm, tuyển dụng)',170],
  ['Bất động sản',290],
  ['Chứng khoán',308],
  ['Vay tiền & tiết kiệm',309],
  ['Crypto, Forex, kênh đầu tư khác',310],
  ['Học ngoại ngữ',291],
  ['Ngành CNTT',294],
  ['Kỹ năng và kinh nghiệm đi làm',295],
  ['Cẩm nang khởi nghiệp',296],
  ['Sự kiện & khóa học',297],
  ['Ô tô & đồ chơi', 305],
  ['Xe máy & Moto', 269],
  ['Xe đạp',306],
  ['Chuyện trò linh tinh™',17],
  ['From f17 with Love',145],
  ['Offline',35],
  ['Thể dục thể thao',287],
  ['Superthreads - Wiki vOz',34],
  ['Ăn uống',289],
  ['Cẩm nang du lịch',298],
  ['Phim - Nhạc - Sách',286],
  ['Chụp ảnh & Quay phim',288],
  ['Các món ăn chơi',207],
  ['Máy tính bàn, linh kiện, mạng',68],
  ['Máy tính xách tay',72],
  ['Điện thoại di động',76],
  ['Mua & bán xe',299],
  ['Thời trang & làm đẹp',300],
  ['Rao vặt Bất động sản',301],
  ['Dịch vụ ăn uống, du lịch',302],
  ['Sim số đẹp & đồ phong thủy',303],
  ['Các sản phẩm, dịch vụ khác',80],
];

export const category = [
  ['Đại sảnh',0,3],
  ['Máy tính để bàn',4,15],
  ['Games',16,20],
  ['Sản phẩm công nghệ',21,27],
  ['Doanh nghiệp & Người dùng',28,32],
  ['Đầu tư & Kinh doanh',33,36],
  ['Học tập và công việc',37,41],
  ['2 bánh - 4 bánh',42,44],
  ['Khu vui chơi giải trí',45,54],
  ['Khu thương mại',54,64]
];
